### ISSUE TITLE
ライブラリの選定等（必要に応じて随時）

### ISSUE THREAD

**Issue by nyohoo** [NewBeLab/NewBeLab-Vue#11]
# バリデーション  

【必要な背景】
プロフィール欄やタグ作成などでテキストの自由記入の形式にした場合は文字数チェックなどで必要と思われる。 

## vuelidate
- [ドキュメント](https://vuelidate-next.netlify.app/)
- vue3に対応している? 
  => `Vuelidate v2.0 supports both Vue 3.0 and Vue 2.x**`
  => 3.6.xは微妙かも
- スター数：6.5k

## VeeValidate
- [ドキュメント](https://vee-validate.logaretm.com/v4/)
- vue3に対応している => `following: Prepare a Vue 3.x project using the [vue-cli](https://cli.vuejs.org/)`
- スター数：9.4k

## vuetifyを利用したバリデーション
- [ドキュメント](https://next.vuetifyjs.com/en/components/forms/)
- 上記ドキュメントの`Rules`のあたりを参照
- フォームなど一部で可能
  =>追加でライブラリを入れる必要はなくなる。
 =>複雑なバリデーションが必要でなければこれで十分かも

**Comment by yoiyoicho** [comment]
ありがとうございます！！！
実際どういうバリデーションをかける必要があるかによりそうですね。
複雑なバリデーションが必要でない＆ふじわらさんが使いたいライブラリがないという状況なら、最後の「vuetifyを利用したバリデーション」でよいのではないかと思いました。

**Comment by nyohoo** [comment]
>実際どういうバリデーションをかける必要があるかによりそうですね。
そうですね！
使いたいライブラリ等はないので、ひとまずはライブラリは入れずVuetifyで対応し、
複雑なバリデーションが必要になりそうだったらそのタイミングで再検討しましょう！
